CONFIG_VERSION=11

# Настройки загрузки видео
TIKTOK_USER=""
DOWNLOAD_LIKED_VIDEOS=true
DOWNLOAD_SAVED_VIDEOS=true

# Настройки Telegram
TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHAT_ID=""

# Настройки Discord (вставьте ваш токен и ID канала)
DISCORD_BOT_TOKEN=""
DISCORD_CHANNEL_ID=""
# Максимальный размер видео в байтах (по умолчанию ~50MiB)
DISCORD_MAX_VIDEO_SIZE=52428800

# Настройки проверки доступности
CHECK_INTERVAL_DAYS=7

# Пытаться скачать failed видео, вдруг их восстановили
HOPE_MODE=false
MAX_RETRIES=3

# Настройки прокси и user-agent
PROXY=""
USER_AGENT=""
CHECK_TIKTOK_AVAILABILITY=true

# Пути к файлам и директориям
# Все пути относительно директории config (или абсолютные)
DATABASE=tiktok_videos.db
DOWNLOADS_DIR=./downloads  # при запуске в докере путь всегда /downloads
TIKTOK_DATA_FILE=user_data_tiktok.json
COOKIES_FILE=cookies.txt
